/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_pigpioj_PigpioI2C */

#ifndef _Included_uk_pigpioj_PigpioBitBangSerial
#define _Included_uk_pigpioj_PigpioBitBangSerial
#ifdef __cplusplus
extern "C" {
#endif

//Author: 9903286
//RX
/*
 * Class:     uk_pigpioj_PigpioBitBangSerial
 * Method:    serialReadOpen
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_uk_pigpioj_PigpioBitBangSerial_serialReadOpen
  (JNIEnv* env, jclass clz, jint gpio, jint baud, jint data_bits);
/*
 * Class:     uk_pigpioj_PigpioBitBangSerial
 * Method:    serialReadInvert
 * Signature: (IZ)I
 */
JNIEXPORT jint JNICALL Java_uk_pigpioj_PigpioBitBangSerial_serialReadInvert
  (JNIEnv* env, jclass clz, jint gpio, jboolean invert);
/*
 * Class:     uk_pigpioj_PigpioBitBangSerial
 * Method:    serialRead
 * Signature: (II)[B
 */
JNIEXPORT jbyteArray JNICALL Java_uk_pigpioj_PigpioBitBangSerial_serialRead
  (JNIEnv* env, jclass clz, jint gpio, jint maxSize);
/*
 * Class:     uk_pigpioj_PigpioBitBangSerial
 * Method:    serialReadClose
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_uk_pigpioj_PigpioBitBangSerial_serialReadClose
  (JNIEnv* env, jclass clz, jint gpio);

//TX
/*
 * Class:     uk_pigpioj_PigpioBitBangSerial
 * Method:    waveClear
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_uk_pigpioj_PigpioBitBangSerial_waveClear
  (JNIEnv* env, jclass clz);

/*
 * Class:     uk_pigpioj_PigpioBitBangSerial
 * Method:    waveAddSerial
 * Signature: (IIIIII[B)I
 */
JNIEXPORT jint JNICALL Java_uk_pigpioj_PigpioBitBangSerial_waveAddSerial
  (JNIEnv* env, jclass clz, jint gpio, jint baud, jint data_bits, jint stop_bits, jint offset, jint numBytes, jbyteArray bytes);

/*
 * Class:     uk_pigpioj_PigpioBitBangSerial
 * Method:    waveCreate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_uk_pigpioj_PigpioBitBangSerial_waveCreate
  (JNIEnv* env, jclass clz);

/*
 * Class:     uk_pigpioj_PigpioBitBangSerial
 * Method:    waveTXSend
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_uk_pigpioj_PigpioBitBangSerial_waveTXSend
  (JNIEnv* env, jclass clz, jint wave_id, jint wave_mode);

/*
 * Class:     uk_pigpioj_PigpioBitBangSerial
 * Method:    waveDelete
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_uk_pigpioj_PigpioBitBangSerial_waveDelete
  (JNIEnv* env, jclass clz, jint wave_id);

#ifdef __cplusplus
}
#endif
#endif
