/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_pigpioj_PigpioI2C */

#ifndef _Included_uk_pigpioj_PigpioI2C
#define _Included_uk_pigpioj_PigpioI2C
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_pigpioj_PigpioI2C
 * Method:    i2cOpen
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_uk_pigpioj_PigpioI2C_i2cOpen
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     uk_pigpioj_PigpioI2C
 * Method:    i2cClose
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_uk_pigpioj_PigpioI2C_i2cClose
  (JNIEnv *, jclass, jint);

/*
 * Class:     uk_pigpioj_PigpioI2C
 * Method:    i2cReadByte
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_uk_pigpioj_PigpioI2C_i2cReadByte
  (JNIEnv *, jclass, jint);

/*
 * Class:     uk_pigpioj_PigpioI2C
 * Method:    i2cWriteByte
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_uk_pigpioj_PigpioI2C_i2cWriteByte
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     uk_pigpioj_PigpioI2C
 * Method:    i2cReadByteData
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_uk_pigpioj_PigpioI2C_i2cReadByteData
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     uk_pigpioj_PigpioI2C
 * Method:    i2cWriteByteData
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_uk_pigpioj_PigpioI2C_i2cWriteByteData
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     uk_pigpioj_PigpioI2C
 * Method:    i2cReadWordData
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_uk_pigpioj_PigpioI2C_i2cReadWordData
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     uk_pigpioj_PigpioI2C
 * Method:    i2cWriteWordData
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_uk_pigpioj_PigpioI2C_i2cWriteWordData
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     uk_pigpioj_PigpioI2C
 * Method:    i2cProcessCall
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_uk_pigpioj_PigpioI2C_i2cProcessCall
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     uk_pigpioj_PigpioI2C
 * Method:    i2cReadBlockData
 * Signature: (II[B)I
 */
JNIEXPORT jint JNICALL Java_uk_pigpioj_PigpioI2C_i2cReadBlockData
  (JNIEnv *, jclass, jint, jint, jbyteArray);

/*
 * Class:     uk_pigpioj_PigpioI2C
 * Method:    i2cWriteBlockData
 * Signature: (II[BI)I
 */
JNIEXPORT jint JNICALL Java_uk_pigpioj_PigpioI2C_i2cWriteBlockData
  (JNIEnv *, jclass, jint, jint, jbyteArray, jint);

/*
 * Class:     uk_pigpioj_PigpioI2C
 * Method:    i2cReadI2CBlockData
 * Signature: (II[BI)I
 */
JNIEXPORT jint JNICALL Java_uk_pigpioj_PigpioI2C_i2cReadI2CBlockData
  (JNIEnv *, jclass, jint, jint, jbyteArray, jint);

/*
 * Class:     uk_pigpioj_PigpioI2C
 * Method:    i2cWriteI2CBlockData
 * Signature: (II[BI)I
 */
JNIEXPORT jint JNICALL Java_uk_pigpioj_PigpioI2C_i2cWriteI2CBlockData
  (JNIEnv *, jclass, jint, jint, jbyteArray, jint);

/*
 * Class:     uk_pigpioj_PigpioI2C
 * Method:    i2cReadDevice
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_uk_pigpioj_PigpioI2C_i2cReadDevice
  (JNIEnv *, jclass, jint, jbyteArray, jint);

/*
 * Class:     uk_pigpioj_PigpioI2C
 * Method:    i2cWriteDevice
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_uk_pigpioj_PigpioI2C_i2cWriteDevice
  (JNIEnv *, jclass, jint, jbyteArray, jint);

/*
 * Class:     uk_pigpioj_PigpioI2C
 * Method:    i2cSwitchCombined
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_uk_pigpioj_PigpioI2C_i2cSwitchCombined
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
